[phases.setup]
nixPkgs = ['nodejs', 'pnpm-8_x', 'python311']
aptPkgs = ['build-essential']

[phases.install]
cmds = ['pnpm install --ignore-scripts --frozen-lockfile']

[phases.build]
cmds = ['pnpm build:storage']

[start]
runImage  =  'debian:bullseye-slim'
onlyIncludeFiles  =  [ './pkg/server-octopus' ]
cmd = './pkg/server-octopus'
