[package]
name = "server-octopus-dao"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../entity" }
migration = { path = "../migration" }

[dependencies.sea-orm]
version = "0.11.1"
features = ["debug-print", "sqlx-sqlite", "runtime-actix-rustls"]
