FROM node:18-bullseye

WORKDIR /app

RUN apt-get update

RUN apt-get install -y python3 python3-pip build-essential

COPY . .

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm build:client


FROM alpine

WORKDIR /app

COPY --from=0 /app/pkg/server-octopus .

CMD ["./server-octopus"]
