FROM node:20-alpine

WORKDIR /app

RUN apk update
RUN apk add --no-cache python3 py3-pip build-base

COPY . .

RUN npm install -g pnpm

RUN pnpm version:prod && pnpm install

RUN pnpm build:storage


FROM node:20-alpine

WORKDIR /app

COPY --from=0 /app/packages/storage/package.json .

COPY --from=0 /app/packages/storage/prisma ./prisma

RUN npm install --omit=dev --legacy-peer-deps

COPY --from=0 /app/packages/storage/dist .

CMD ["node", "main.js"]
