http:
    routers:
        view:
            rule: "Host(`serverhub.app`)"
            service: "service-view"
            tls:
                certResolver: myresolver
            entryPoints:
                - websecure

        client:
            rule: "Host(`client.serverhub.app`)"
            service: "service-client"
            tls:
                certResolver: myresolver
            entryPoints:
                - websecure

        server:
            rule: "Host(`server.serverhub.app`)"
            service: "service-server"
            tls:
                certResolver: myresolver
            entryPoints:
                - websecure

    services:
        service-view:
            loadBalancer:
                servers:
                    - url: "http://view:3000"

        service-server:
          loadBalancer:
              servers:
                  -   url: "http://server:3001"

        service-client:
            loadBalancer:
                servers:
                    - url: "http://client:3002"
