entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yaml

certificatesResolvers:
  myresolver:
    acme:
      email: "admin@serverhub.app"
      storage: "acme.json"
      tlsChallenge: {}
