//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::rbac::permissions::Entity as Permissions;
pub use super::rbac::role_permissions::Entity as RolePermissions;
pub use super::rbac::roles::Entity as Roles;
pub use super::rbac::user_roles::Entity as UserRoles;
pub use super::rbac::users::Entity as Users;
